project:
  type: website

website:
  title: "Image2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
      - section: "One Shot Imaging"
        contents:
        - OneShot/abstract.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
