project:
  type: website

website:
  title: "Image2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
      style: "docked"
      search: true
      contents:
      - section: "Abstracts"
        contents:
        - file: OneShot/abstract.qmd
          text: "One Shot Imaging"
        - text: "Coupled physics inversion"
          file: yin2023IMAGEend2end/abstract.qmd
        - text: "Bayesian FWI"
          file: BayesianFWI/abstract.qmd
        - text: "Bayesian Kriging"
          file: BayesianKrig/abstract.qmd
        - text: "Leakage Detectibility with Vision Classifier"
          file: DetectabilityWithVision/abstract.qmd
        - text: "3D survey design"
          file: zhang2023IMAGEsg/abstract.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


execute:
  freeze: auto
