project:
  type: website

website:
  title: "Image2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
      - section: "One Shot Imaging"
        contents:
        - OneShot/abstract.qmd
      - section: "Coupled physics inversion"
        contents:
        - yin2023IMAGEend2end/abstract.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


execute:
  freeze: auto
